- import_tasks: net.yml
  tags:
    - host
- import_tasks: pf.yml
  tags:
    - host
- import_tasks: sshd.yml
  tags:
    - host
- import_tasks: repo.yml
  tags:
    - host
- import_tasks: packages.yml
  tags:
    - host
- import_tasks: zpool.yml
  tags:
    - host
- import_tasks: iocage.yml
  tags:
    - host
- import_tasks: user.yml
  tags:
    - host
- import_tasks: timezone.yml
  tags:
    - host
- import_tasks: ssmtp.yml
  tags:
    - host
- import_tasks: ntp.yml
  tags:
    - host
- import_tasks: tarsnap.yml
  when: tarsnap_enabled
  tags:
    - host
