# handlers file for jail_host
- name: Start iocage
  service:
    name: 'iocage'
    state: started

- name: Reload pf
  service:
    name: 'pf'
    state: reloaded

- name: Reload host sshd
  service:
    name: 'sshd'
    state: reloaded

- name: Reload syslogd
  service:
    name: 'syslogd'
    state: reloaded
